name: expando
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - gym=0.18.0
  - pyglet=1.5.15
  - pip:
      - hydra-core==1.0.6
      - stable-baselines3[extra]==0.11.1
