# @package _global_
piece_types:
  empty:
    _target_: gym_env.game.pieces.Empty

  farm:
    _target_: gym_env.game.pieces.Farm
    population_increase: 1
    reward_size: 0.1
    reward_delay: 0
    ignore_diagonal: True

  city:
    _target_: gym_env.game.pieces.City
    room_capacity: 0.5